### ISSUE TITLE
Map div into another div generates 'TypeError: a is undefined'

### ISSUE THREAD

**Issue by jckermagoret** [kekscom/osmbuildings#101]
Hello,
first, thanks for your project.

When I put a div around the div containing the map like the following:
<div>
    <div id="map"></div>
</div>

I get the following error in FF:
* TypeError: a is undefined

In Chrome:
* Uncaught TypeError: Cannot read property '0' of undefined (OSMBuildings.debug.js:5462)

Any ideas?

JC

**Comment by kekscom** [comment]
Any chance to see it live somewhere?
