### ISSUE TITLE
No/Bad response from building server

### ISSUE THREAD

**Issue by williamhaw** [kekscom/osmbuildings#102]
Similar issue to https://github.com/OSMBuildings/OSMBuildings/issues/90

GET http://data.osmbuildings.org/0.2/anonymous/tile/18/206730/130112.json
GET http://data.osmbuildings.org/0.2/anonymous/tile/18/206730/130111.json
GET http://data.osmbuildings.org/0.2/anonymous/tile/18/206729/130111.json

These three return either 401 Unauthorized or 400 Bad Request.

However, 

GET https://data.osmbuildings.org/0.2/anonymous/tile/15/17380/11015.json
GET https://data.osmbuildings.org/0.2/anonymous/tile/15/17379/11015.json

return a JSON file.

**Comment by kekscom** [comment]
You are trying to fetch tiles out of zoom range. 15..16 is accepted.
