### ISSUE TITLE
Marker change when in shadow

### ISSUE THREAD

**Issue by jclevenne** [kekscom/osmbuildings#109]
Hello

Thank you so much for providing such a great map. 
Is it possible to know (by a function or other) if a specific geographical point at a specific date and time is in the shadow or in the sun? My goal is to change the color of a marker when this one is in the sunlight or under the shade of the buildings.

Thanks for your invaluable support!

**Comment by kekscom** [comment]
Hi,
Maybe that is possible but would go far beyond scope.
A hack would be reading shadow layer pixel by pixel and doing some tests.
Alternative is this one from our drawer: https://github.com/OSMBuildings/pg-shadows
Calculates shadows in PostGIS.

**Comment by jclevenne** [comment]
Thank you!
I succeeded using the method getImageData in the way you suggested (reading pixel by pixel on shadow layer).

**Comment by kekscom** [comment]
Glad it helped. If there is a chance to share your solution, please do.
Cheers
