### ISSUE TITLE
Filtered GeoJSON tiles

### ISSUE THREAD

**Issue by hrishiballal** [kekscom/osmbuildings#110]
Hello, Thank you for the continued work on this, it is really amazing. 

I have a specific question not necessarily a feature request. When you use the addGeoJSONTiles (https://osmbuildings.org/documentation/#method-addGeoJSONTiles) method to load OSM tiles from tile server, is there a way to filter out some features? 

I want to load some existing buildings but not all. E.g. show all buildings except around 500m buffer around a park. How would / could something like this work?

**Comment by kekscom** [comment]
Hi Hrishi,
You could use the loadfeature event for it. That gets you full access to the feature upon load and you can modify it or return null.
The catch is, we are going to deprecate that with next version.
The replacement will allow show/hide at any time.
But also it’s unlikely we are passing geometry.
So how would you figure out affected features?
There is room for some ideas 😀

**Comment by kekscom** [comment]
We did not act for a way too long time. Please reopen if this is still urgent.
