### ISSUE TITLE
Whether leaflet loads OSMBuildings can rotate the map

### ISSUE THREAD

**Issue by BTF-Sang** [kekscom/osmbuildings#113]
I loaded the leaflet map and found that I can't drag and drop the map with the mouse,
      It is equivalent to look down at buildings, I can not rely on leaflet only use OSMBuildings but can rotate the angle.
      Trouble to ask the leaflet to load OSMBuildings can rotate the angle?

**Comment by BTF-Sang** [comment]
Wrap again

**Comment by kekscom** [comment]
OSMBuildings for Leaflet can't neither tilt or rotate.
