### ISSUE TITLE
Running OSMbuildings-leaflet in app instead of CDN

### ISSUE THREAD

**Issue by corrigancd** [kekscom/osmbuildings#116]
I came across this project last week for the first time and nice job!

Super interested in putting this in a leaflet project and was curious if it's possible to implement this by putting the reference to OSMbuildings-leaflet.js in my app rather than specifying it in the html head? If so is there an example of the implementation somewhere? What I'd like like to do is be able to turn 1 instance on or off based on a condition. 

I've tried to add it to my app.js and found d that global is undefined, which is a problem for the requestAnimationPane(). I understand that the problem is that the file executes too soon?

Thanks in advance and would be happy to clarify anything (or even work on a solution ;) ).

**Comment by kekscom** [comment]
Could you post some source code of what you're trying please?

**Comment by corrigancd** [comment]
Thanks for the quick response. I'd suggest closing this for now as there are a few other things that will need to be figured out in order for me to outline an suitable example for you. Apologies.
