### ISSUE TITLE
Displaying large objects at low zoom levels

### ISSUE THREAD

**Issue by flightltd** [kekscom/osmbuildings#117]
Hi,

I am successfully displaying large 3D catchment areas but only at zoom level 15 and above and I wish to display them down to levels 4 or 5. I saw in another issue that there is a MIN_ZOOM setting in constants.js but I can't locate this file. Could you please direct me to it?

Many thanks.

**Comment by HANBGX** [comment]
has the same tb,plz help

**Comment by jocelyn-cazes** [comment]
For OSMBuildings-Leaflet.js (2.5D), find the G var originally set to 15, change to desired.
For OSMBuildings.js (3D) find the MIN_ZOOM var originally set to 15, change to desired.
& Enjoy.
