### ISSUE TITLE
Error 429: Too many requests.

### ISSUE THREAD

**Issue by popepay** [kekscom/osmbuildings#118]
Hello,

I am attempting to use OSM Buildings with leaflet. 
I got it to work following this tutorial for about 20s before it stopped due to 
_Failed to load resource: the server responded with a status of 429 (Too Many Requests)_

This is a simple test interface, on my own computer (single client), just navigating around a single city at zoom levels around 16. 

I could not find a way to register a key without a $99/month subscription. Is there a way to pay as you go? 
Or limit the building modeling when the map becomes static (the user stops moving around)?

Thank you

**Comment by kekscom** [comment]
It seems your testing behaviour and some connection parameters indicate you're trying a bulk download.
We're usually experiencing excessive abuse of the service so there is no chance to lift the limits.
However, you might try a different browser and place your test files on a regular web server.
If this doesn't help, please get in touch via email/contact form.
