### ISSUE TITLE
No buildings on HTTPS

### ISSUE THREAD

**Issue by popepay** [kekscom/osmbuildings#119]
I cannot load the API on a secure (https) connection. 

I have tried forcing all connections to https, but that did not work
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> `

It seems the main OSMBuildings api got changed to work on HTTPS. Any chance we could reproduce the changes for this API as well? 
https://github.com/OSMBuildings/OSMBuildings/issues/103

thank you

**Comment by kekscom** [comment]
Sounds like something different. Could you provide a link to your website or a Codepen setup?
Probably just a failing URL & error message.
Thanks.

**Comment by popepay** [comment]
See attached screenshot. 
The same exact code words if I load the website on _http_, but breaks on _https_

![Screen Shot 2020-02-18 at 1 26 39 PM](https://user-images.githubusercontent.com/17018621/74779510-7f043700-5252-11ea-909c-2cee7dc07fb3.png)

**Comment by kekscom** [comment]
It looks like you have either not explicitly addressed the API or it's done with 'http'.
Please see https://osmbuildings.org/documentation/leaflet/ 
`var osmb = new OSMBuildings(map).load('https://{s}.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json');
`
If this doesn't solve it, please provide a testable code example.
