### ISSUE TITLE
Add GeoJSON data at leaflet.js

### ISSUE THREAD

**Issue by CakirEfekan** [kekscom/osmbuildings#122]
Is that possible to add GeoJSON data with default osmbuildings datas.
The "setData" deletes osmbuildings datas, but i want to use both of them. Are there any solution?

**Comment by kekscom** [comment]
Yes this is an exclusive function. Can't promise a change soon.

**Comment by CakirEfekan** [comment]
Hi again, i found a solution. 
these codes:
https://github.com/kekscom/osmbuildings/blob/b6f8c1b6332255857428405673cbfb0ffaa3ff3c/dist/OSMBuildings-Leaflet.js#L681-L685
should be like these:
https://github.com/kekscom/osmbuildings/blob/95311aafd10d5ae3bbb2feb9ac1198ef0dd1dff5/dist/OSMBuildings-Leaflet.js#L681-L689

These are from my forked repo but i don't know how can i embed code, for this reason i show code blocks as from your repo. 
Sorry for this mess.

**Comment by kekscom** [comment]
Official solution is here: #009f972
Thank you for bringing this up.
