### ISSUE TITLE
OSM Buildings JS libraries

### ISSUE THREAD

**Issue by adam314315** [kekscom/osmbuildings#125]
Hello,

@kekscom I just started to use the osmbuilding library to create 3D buildings on maps but I am a bit confused about the 2 versions of the javascript library.

Could you then describe  the best usage and difference between the standalone WebGL version of OSM Buildings located under https://github.com/OSMBuildings/OSMBuildings and the current repo https://github.com/kekscom/osmbuildings. So far from my understanding the standalone version only relies on OSMBuildings js and css whereas the kekscom/osmbuildings version seems to extend Leaflet or Openlayer. 

Also I can see the 3D building rendering are different between the 2 versions (with more transparency for instance on keskom/osmbuildings). Is there any css or solution to align them?

Thanks in advance for your explanation.

**Comment by kekscom** [comment]
Hi @adam314315, your explanation about differences is correct.

In order to adjust transparency in this version here you may have to change parts of the code.

**Comment by adam314315** [comment]
Ok I will try. Thanks for your reply.
