### ISSUE TITLE
Impact: Fix building occlusion

### ISSUE THREAD

**Issue by bennlich** [kekscom/osmbuildings#34]
Howdy! I just pulled the latest changes from the repo, and it looks like the z-indexes of some of my buildings are behaving strangely. I took a couple screen shots:

![screen shot 2013-06-25 at 3 47 18 pm](https://f.cloud.github.com/assets/704368/706263/62762ce0-dde9-11e2-9387-5579a57184d1.png)
![screen shot 2013-06-25 at 3 47 28 pm](https://f.cloud.github.com/assets/704368/706264/627ec24c-dde9-11e2-85cc-1f55aee33a2b.png)

Notice in the bottom image how the left teal building moves in front / on top of the shorter blue building. I hadn't fetched the latest repo in a while, so I'm not sure which commit is the culprit.

I also noticed that many of my buildings appear much taller than they used to.

I'll start looking at the new commits.

**Comment by kekscom** [comment]
Honestly, a fix is unlikely anytime soon, if at all.
