### ISSUE TITLE
OpenLayers 3 testing

### ISSUE THREAD

**Issue by geochasm** [kekscom/osmbuildings#40]
Hello - 

Any activity or plans for testing OSM Buildings with OpenLayers 3 - http://ol3js.org/

Thanks

Chad

**Comment by KorzhovDmitry** [comment]
Hello, now osm buildings dont work with OpenLayers 3? 
I did't find any information about that.

**Comment by kekscom** [comment]
Hi! There is still no official support for OL3.

**Comment by KorzhovDmitry** [comment]
And with Cesium dont work to?

**Comment by kekscom** [comment]
You may use the data with Cesium as it is a 3d engine on it's own.
