### ISSUE TITLE
Add support for simple roof shapes

### ISSUE THREAD

**Issue by waldyrious** [kekscom/osmbuildings#49]
per #14. I assume the [roofs](https://github.com/kekscom/osmbuildings/tree/roofs) branch deals with this. Supported roof shapes should ideally be those listed [here](http://wiki.openstreetmap.org/wiki/Simple_3D_Buildings#Roof).

**Comment by ruester** [comment]
Is there something done recently? I would really like to have more roof types too. Since LoD2 data gets more and more common...
Currently the roof branch seems to be deleted.

**Comment by kekscom** [comment]
Just shocked for how long this is open. However, priorities have been a lot different last year.
I have newer code for the WebGL version of OSM Buildings, but that's still not ready to use.
Many peaople are still very interested so the pressure is high, but can't promise you any dates.
If there is any chance to help, I'd be glad.

**Comment by pbb72** [comment]
Does this mean roof shape support has been added, or that you will never add it?

**Comment by kekscom** [comment]
Valid question :-)
It won't be added in *this* variant of the library. We are aiming for a WebGL solution instead.
