### ISSUE TITLE
Clipping issues where buildings/building-parts touch each other

### ISSUE THREAD

**Issue by eliasp** [kekscom/osmbuildings#59]
See [this building](http://osmbuildings.org/?lat=48.53765&lon=9.03836&zoom=19) for example.

Move the viewport slightly to the left/right to see a weird clipping issue between the building-parts.

As GIF:  
![osmb-anim](https://f.cloud.github.com/assets/48491/2416668/b7cc5d34-ab09-11e3-9d9f-fa76b4dcde04.gif)

**Comment by AbelVM** [comment]
Maybe taking relative heights into account, could fix some cases. Test case: two nested polygons, outer' height=1, inner' height = 10:
![Image of practical case](http://s1.postimg.org/bt431jr7j/osmberror.png)
(Labels are placed in centroids)
Higher buildings roofs should never be overlapped by lower buildings roofs

**Comment by kekscom** [comment]
Problem here is overlapping. I can easily sort heights and also distances of object centers from view point. It's also possible to check for intersection but that is a very costly operation.
For the 2.5D renderer I see only web workers as an option to handle all the sorting.

**Comment by AbelVM** [comment]
So, you get the center of each 2D polygon, extrude it to its height and then apply Painter's algorithm, setting a z-index to each 3D building (as a whole) using its 2D center.

I've been playing for some hours triying to make a 3D calculation of z-index sorting without performance hit and keeping Painter's algorithm as core to avoid deep changes. No success. 

The only way to keep this algorithm is checking each poligon 3D center, I mean each wall and ceiling as 3D polygons. And even this way, nested or concave buildings will fail. Painter's algorithm has this issue.

Maybe [Newell's Algorithm](http://en.wikipedia.org/wiki/Newell%27s_algorithm) could help with this cases. Will play some more and post results if any.

**Comment by kekscom** [comment]
Hi, Thanks for putting in the effort. I'm curious for a better solution as well but can't make it right now.
I ended up with these conclusions:
1. It should be feasible to improve the current 2D sorting rules to eliminate more glitches.
2. Performance wise, there is likely no proper solution at all for nested objects. Maybe it has to be accepted.
3. I see potential in handling faces instead of objects (like you do). It could be even faster to draw that way.
Keep going!
