### ISSUE TITLE
Allow initialization without adding to a map / support for layers control

### ISSUE THREAD

**Issue by amenk** [kekscom/osmbuildings#70]
Use case: Initialize 3D buildings but show them only after selection in the layer control.

Currently a map object must be supplied on initialization - so we can not add it to the layer control without directly showing the buildings.

Current workaround: Remove layer immediately after initialization.

**Comment by kekscom** [comment]
changed by a3b57a7427d476e5848d6a9378c1b5618bcd9317

You can now do:
~~~
var osmb = new OSMBuildings();
L.control.layers({}, { Buildings:osmb }).addTo(map);
osmb.addTo(map).load()
~~~

**Comment by amenk** [comment]
Cool thanks
