### ISSUE TITLE
geometries of shadows?

### ISSUE THREAD

**Issue by rajanski** [kekscom/osmbuildings#77]
Hi I just stumbled upon this amazing  leaflet plugin! Especially the shadows functionality is just great! Is there a way to return the geometries for the shadows ?
best,

R

**Comment by kekscom** [comment]
There is no API for that, but check the source in https://github.com/kekscom/osmbuildings/blob/master/src/layers/Shadows.js

You'll need the sun position and buildings geometry. Then its just a projection.

If you need a specific solution, get in touch.
