### ISSUE TITLE
Some examples of how to get hights from wms server

### ISSUE THREAD

**Issue by am2222** [kekscom/osmbuildings#78]
Hi,
I am intrested to find out that if it is possible to get building hight and roof shapes from a wms server such as geoserver and use those data in osmbuildings.Is this even possible?
how can I learn more about it?
Thank you so much

**Comment by kekscom** [comment]
Hi,
You'll probably need a WFS source. Even then, height and roof shape might not be present in the data.
Once your data is clarified, its likely a transformation like from GML to GeoJSON.
At that point, I can help with further assistance.

**Comment by am2222** [comment]
Thank you  for your answer,I have worked with WFS services but have not try transforming from tham to GeoJSON, the only way is transforming to GEOJSON and then using this javascript liberary?right?

**Comment by kekscom** [comment]
Any kind of JSON will be consumed and the final internal structure is kind of GeoJSON. That's why a direct conversion to GeoJSON would make a lot of sense. Though it might not be trivial.

**Comment by am2222** [comment]
Thank you for your great help
