### ISSUE TITLE
Custom GeoJSON: minHeight / height issue

### ISSUE THREAD

**Issue by hrishiballal** [kekscom/osmbuildings#81]
When minHeight is negative for a geoJSON feature, the height needs to be greater than 8 in my tests. e.g. minHeight = -120 and height = 0 does not work however minHeight = -120 and height = 10 works. 

There should be no dependency between minheight and height parameters.

**Comment by kekscom** [comment]
We did not act for a way too long time. Please reopen if this is still urgent.
