### ISSUE TITLE
OSMBuildings over HTTPS 

### ISSUE THREAD

**Issue by Copywright** [kekscom/osmbuildings#85]
I'm using OSMBuildings for my project here: https://peeltheapple.herokuapp.com/

Check the JS console, you'll see:

![HTTPS issues over Heroku](https://dl.dropboxusercontent.com/u/15727879/Screenshot%202015-08-11%2012.56.37.png)

**Comment by kekscom** [comment]
Maybe I'll find an interim solution until letsencrypt.com is ready.

**Comment by kekscom** [comment]
Done and working.
