### ISSUE TITLE
Broken polygon winding detection

### ISSUE THREAD

**Issue by kekscom** [kekscom/osmbuildings#86]
http://osmbuildings.org/?lat=52.52257&lon=13.33810&zoom=19

**Comment by AbelVM** [comment]
Maybe: https://github.com/Turfjs/turf-rewind

**Comment by kekscom** [comment]
I'll give it a try. Thanks

**Comment by kekscom** [comment]
Tested but no success.
From what I see on osm.org ist not mapped properly.
The inner polygon seems to be a standalone building.

However, I'll keep Turf's code as it is more compact than mine.
Thanks
