### ISSUE TITLE
Callback when all buildings are loaded for frame

### ISSUE THREAD

**Issue by stevepepple** [kekscom/osmbuildings#87]
Have you considered adding a callback function to the .load() method of the osbm class? 

I'm working on a app that geocodes and reloads buildings. Exposing the callback request in the method, would make it easy to know when the current set of building are loaded. 

I'm using version 0.2.2b

Love the library overall!

**Comment by kekscom** [comment]
Hi, Thanks fo using the lib!
I didn't consider that. Especially as my not immediately start loading nor it may aned anytime bacause of movement.
The GL version has a mechanism telling you it's busy or not. Would that be helpful?

**Comment by stevepepple** [comment]
Yes. Let me try out the GL version.

I see your point. After looking more closely at the code, I see that there are a significant number of tile calls that get made based upon map events. So having a callback expected for those to complete is probably not the best practive.

**Comment by kekscom** [comment]
I'm closing this. Feel free to get back if there is changed requirements/ideas.
