### ISSUE TITLE
rendering relations?

### ISSUE THREAD

**Issue by mtoupsUNO** [kekscom/osmbuildings#88]
Hi, osmbuildings is very nice, thanks!

It seems there is a problem rendering relations (tagged as building=yes). For example, neither of these relations seem to be rendered in osmbuildings:

https://www.openstreetmap.org/relation/4597513
https://www.openstreetmap.org/relation/4598971

These are located here:

http://osmbuildings.org/?lat=29.94945&lon=-90.07921&zoom=17&rotation=0

I am not a big fan of using relations here instead of ways, but another user mapped the buildings this way and it does appear valid to me. Shouldn't these be rendered?

Thanks for checking on this!

**Comment by kekscom** [comment]
Hi Matt,
I have a lot of improvements on the dome, but nothing on the King Center yet.
Probably need more advice what tag/relation combination to take care of.
Have a look.

**Comment by kekscom** [comment]
Multipolygon handling got a lot of improvement just now.
Relations of LineStrings remain topic to be solved.
