### ISSUE TITLE
No search for "short_name"

### ISSUE THREAD

**Issue by Atalanttore** [kekscom/osmbuildings#89]
Hi,

OSMBuildings doesn't search for the value in "short_name" keys.

Regards,
Ettore

**Comment by kekscom** [comment]
Hi Ettore,
We will use a different search service soon!
However, we have no influence on how it's done nor is OSM Buildings anyhow a search service.
Regrads,
Jan

**Comment by kekscom** [comment]
Could you give it another try now?
