### ISSUE TITLE
Any documentation on "very basic OL3 support"?

### ISSUE THREAD

**Issue by tomchadwin** [kekscom/osmbuildings#92]
I've added the Leaflet code to qgis2web (https://github.com/tomchadwin/qgis2web), and it works brilliantly. I'm now trying to add support for qgis2web's OL3 output. I've used the OL3 JS file in `/dist`, but I'm getting an error.

Can anyone tell me what is possible/not possible with OL3, and how to do it?

**Comment by tomchadwin** [comment]
The error thrown is

```
OSMBuildings-OL3.debug.js:2160:
TypeError: Cannot read property 'appendChild' of null(…)
```

**Comment by kekscom** [comment]
Looks like it can't append the OSM Buildings layer to some map container.
I'll have a look.

**Comment by tomchadwin** [comment]
It's the output from qgis2web:

- install qgis 2.14
- install plugin qgis2web
- open a polygon layer
- apply a 2.5d style
- start qgis2web

That gives the error above.

**Comment by kekscom** [comment]
Could you provide me a sample site with qgis2web output or could you share screen?

**Comment by tomchadwin** [comment]
I'll do an export and upload it somewhere. I'll see if I can also simplify it a bit. Share screen is an option - I'm in the UK,  as far as timezone goes.

**Comment by tomchadwin** [comment]
Zip is here: https://github.com/tomchadwin/osmbuildings/blob/master/osmbuildings-ol3.zip

**Comment by kekscom** [comment]
:+1:  Helps me to get the error. I'll check.

**Comment by kekscom** [comment]
I've added a fix. Please retry.

**Comment by tomchadwin** [comment]
Brilliant - that appears to have sorted it. Many thanks!

**Comment by tomchadwin** [comment]
This version is now used in qgis2web master, and on initial tests seems to work a treat. Thanks once again.

**Comment by kekscom** [comment]
You're welcome :-)
