### ISSUE TITLE
Always show buildings (2.5 ver)

### ISSUE THREAD

**Issue by ivanmiro** [kekscom/osmbuildings#93]
Buildings hides on small scale.
Is there a way to always show their?

**Comment by kekscom** [comment]
For 2.5D not really. At some point the whole application becomes unusable.
If this is urgent, you can modify zoom limit here:
https://github.com/kekscom/osmbuildings/blob/master/src/variables.js#L15
Unless you do that in dist folder, a new build is required.

**Comment by ivanmiro** [comment]
Hello! Thx for reply! Variables - is what I need!
