### ISSUE TITLE
Namespace or allow user to set JSON field names

### ISSUE THREAD

**Issue by tomchadwin** [kekscom/osmbuildings#94]
`height`, `wallColor`, and `roofColor` could conceivably already be present in a dataset - certainly `height`. Is it worth prefixing the required variable names with `osmb_`?

**Comment by kekscom** [comment]
I don't think that'll get in. If those properties are present, they're most likely placed for visual representation.
Otherwise, if those are pure data, I could imagine to have a method like each() in Classic OSM Buildings in order to modify properties as you like.

**Comment by kekscom** [comment]
Addition: you are already referring to Classic version. Then give each() a try please.
