### ISSUE TITLE
Openlayers3 lag

### ISSUE THREAD

**Issue by tomchadwin** [kekscom/osmbuildings#96]
The Leaflet rendering is nice and fast, whereas Openlayers 3 lags - the buildings redraw after a map zoom/pan has already completed.

**Comment by kekscom** [comment]
Whole OL3 support lags behind.
OpenLayers is generally much slower than Leaflet and API is much worse.
Fixing anything means even further dive in in order to hack something.
Honestly I can't prioritize this.
If there is anything you can perhaps contribute, I'm glad to assist.
