### ISSUE TITLE
zooming on mobile devices,  buildings position is wrong

### ISSUE THREAD

**Issue by emreesirik** [kekscom/osmbuildings#97]
When trying to zoom on mobile devices, buildings position is looking like shifting.
But after panning to map, position is fixed to right coordinate

**Comment by kekscom** [comment]
Is there any chance to demo this? Video would be perfect.
Otherwise just device + OS.
At least I can't reproduce it on devices with iOS 9.2+. Will try Android asap.

**Comment by kekscom** [comment]
Fixed.
