### ISSUE TITLE
building:levels are not working in classic 2.5D

### ISSUE THREAD

**Issue by sanjeevyanala** [kekscom/osmbuildings#99]
I have added a geojson, the properties of geojson is like below mentioned:
 "properties": {
      "color": "rgb(255,200,150)",
      "height": 250,
      "building:levels" :7,
      "minHeight": 50,
      "roofColor": "#FFDA33",
      "roofMaterial":"wood",
      "material": "material",
      "shape":"cylinder",
      "roofShape":"gabled",
      "roof:shape":"mansard"
    }
But here building:levels are not working. How can i apply ?

**Comment by kekscom** [comment]
It's just 'levels'.

**Comment by kekscom** [comment]
Just in case: if height is available as well, it would take precedence.

**Comment by sanjeevyanala** [comment]
Hi, Help me, I have written like this, even though it is not working...
"properties": {
     "color": "rgb(255,200,150)",
     "levels": 9,
     "height": 250,
     "building:levels" :7,
     "minHeight": 50,
     "roofColor": "#FFDA33",
     "roofMaterial":"wood",
     "material": "material",
     "shape":"cylinder",
     "roofShape":"gabled",
     "roof:shape":"mansard"      
    }
Could you give me a working example of levels.

**Comment by kekscom** [comment]
I might be missing the point but this works perfectly fine: http://codepen.io/osmbuildings/pen/EyXwXv

**Comment by sanjeevyanala** [comment]
Thanks, it's working fine, but is it possible to show floors (levels) with different colors ?

**Comment by kekscom** [comment]
Alright.
For styled levels you really need to provide different 3D objects. Properties minHeight or minLevel allow you to set the vertical position of an object.
For a while district this would of course blow the 3D engine.
